# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-31 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.TextField(null=True),
        ),
    ]
